modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "temper"
version = "${version}"
displayName = "Temper"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.temper]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.temper]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.temper]]
modId = "architectury"
type = "required"
versionRange = "[20.0.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "temper.mixins.json"
