modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/kevdev-code/Temper-mod/issues"

[[mods]]
modId = "temper"
version = "${version}"
displayName = "Temper"
authors = "kevdev-code"
displayURL = "https://github.com/kevdev-code/Temper-mod"
description = '''
Replaces vanilla tool progression with a four-part crafting system: head, handle, binding and reinforcement, each made from a different material. Works on Fabric and NeoForge.
'''
#logoFile = ""

[[dependencies.temper]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.temper]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.temper]]
modId = "architectury"
type = "required"
versionRange = "[20.0.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "temper.mixins.json"
